language: node_js
sudo: required
node_js:
- 10
before_install:
- npm install -g qunit
- npm install file-system
- npm install eslint
script:
- qunit
notifications:
  email:
    recipients:
    - thecodingnerd256@gmail.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      - thecodingnerd256:KwKTkJ113gJF0llSrHDv5ENt#githubio
    on_success: always # default: always
    on_failure: always # default: always